services:
  api:
    build: .
    container_name: oshen_extractor_api
    ports:
      - "9009:9009"
    volumes:
      - .:/app
    environment:
      - OSHEN_EXTRACTOR_TOKEN=${OSHEN_EXTRACTOR_TOKEN}
      - OSHEN_EXTRACTOR_BASE_URL=${OSHEN_EXTRACTOR_BASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - WHATSAPP_REDIS_QUEUENAME=${WHATSAPP_REDIS_QUEUENAME}
