services:
  api:
    build: .
    container_name: oshen_extractor_api
    ports:
      - "9009:9009"
    volumes:
      - .:/app
    environment:
      - OSHEN_EXTRACTOR_TOKEN=${OSHEN_EXTRACTOR_TOKEN}
      - OSHEN_EXTRACTOR_BASE_URL=${OSHEN_EXTRACTOR_BASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - WHATSAPP_REDIS_STREAM=${WHATSAPP_REDIS_STREAM}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - DEFAULT_EVOLUTION_INSTANCE_NAME=${DEFAULT_EVOLUTION_INSTANCE_NAME}
      - WEBHOOK_PUBLIC_URL=${WEBHOOK_PUBLIC_URL}
    networks:
      - infra_evolution_net

networks:
  infra_evolution_net:
    external: true
